// import Barchat from "./components/Barchat";
// import Header from "./components/Header";
// import Recentorders from "./components/Recentorders";
import Sidebar from "./components/Sidebar";
// import Topcards from "./components/Topcards";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        
      <body className="{inter.className} bg-gray-100">
        
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
